LIST p=18f4520	;defines the tyoe of pic microcontroller
#include<P18F4520.INC>	;INCLUDE DIRECTORIES FOR THIS MICROCONTROLLER
;GLOBAL STATEMENTS DEFINED HERE

ORG 0X20	;ORIGIN OF CODE
GOTO START	;JUMP TO LABEL CALLED START
START MOVLW 0X10 ;MOVE HEX 1 TO WORD REGISTER
	ADDLW 0X01 ;ADD CONTENTS OF WREG AND THE LITERAL 0X0F. RESULT IS STORED BACK IN WREG
	INCF W  ;GUESS TO INCREMENT THE WORKING REGISTER
END